### ISSUE TITLE
Is there a way to get an Update for newer Minecraft Versions?

### ISSUE THREAD

**Issue by 001Marlon** [Focamacho/KeepTheResourcePack#3]
Fabric 1.20.2 would be nice.

**Comment by focamacho** [comment]
Newers versions are now available. I still need to update to 1.20.3-4, minecraft changed many server resourcepack stuff in those versions so i'll do it later.

You can find them here:
**CurseForge**
Forge -> https://curseforge.com/minecraft/mc-mods/keep-the-resourcepack
Fabric -> https://curseforge.com/minecraft/mc-mods/fabric-keep-the-resourcepack

**Modrinth**
Forge & Fabric -> https://modrinth.com/mod/keep-the-resourcepack

Obs: CurseForge Fabric project and Modrinth project are still under review, so the page can be unavailable until it gets approved.
